#!/bin/bash
FP_DATA=/opt/ml/input/data/cfg/coco.data
FP_YOLO=/opt/ml/input/data/cfg/yolov4.cfg
FP_WEIGHT=/opt/ml/input/data/weights/yolov4.conv.137
darknet detector train $FP_DATA $FP_YOLO $FP_WEIGHT -dont_show -map